import { useState } from 'react';
import { useParams } from 'wouter';
import { ArrowUp, Bot, Check, Clock3, Loader2 } from 'lucide-react';
import { useGetBusiness, useGetAssistant, useSendChatMessage } from '@workspace/api-client-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export function PublicChatPage() {
  const { businessSlug = 'your-business' } = useParams<{ businessSlug: string }>(); const { data: business } = useGetBusiness(); const { data: assistant } = useGetAssistant(); const send = useSendChatMessage(); const [input, setInput] = useState(''); const [conversationId, setConversationId] = useState<string | null>(null); const [messages, setMessages] = useState<{ role: string; content: string }[]>([{ role: 'assistant', content: assistant?.greeting || `Hi there. How can we help${business?.name ? ` at ${business.name}` : ''}?` }]);
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!input.trim() || send.isPending) return; const message = input.trim(); setMessages([...messages, { role: 'user', content: message }]); setInput(''); send.mutate({ businessSlug, data: { message, conversationId } }, { onSuccess: response => { setConversationId(response.conversationId); setMessages(current => [...current, { role: 'assistant', content: response.message }]); } }); };
  return <div className="min-h-[100dvh] bg-[#f4f7f7]"><header className="mx-auto flex max-w-3xl items-center justify-between px-5 py-5"><div className="flex items-center gap-2.5"><div className="flex size-8 items-center justify-center rounded-[10px] bg-[#15252a] text-[#53ceb0]"><Bot className="size-4" /></div><div><p className="text-sm font-extrabold tracking-[-0.03em]">{assistant?.name || 'LeadFlow assistant'}</p><p className="flex items-center gap-1 font-mono text-[9px] uppercase tracking-widest text-[#159477]"><span className="size-1.5 rounded-full bg-[#1db58f]" /> Online now</p></div></div><div className="hidden items-center gap-1.5 text-[10px] text-[#76888c] sm:flex"><Clock3 className="size-3.5" /> Usually replies instantly</div></header><main className="mx-auto max-w-2xl px-4 pb-10 pt-10"><div className="mb-7 text-center"><div className="mx-auto mb-4 flex size-14 items-center justify-center rounded-2xl bg-[#d7f1e9] text-[#159477]"><Bot className="size-7" /></div><h1 className="text-2xl font-extrabold tracking-[-0.06em]">{business?.name || 'Your next project'} starts here.</h1><p className="mt-2 text-sm text-[#718286]">Tell us what you’re looking for. We’ll point you in the right direction.</p></div><div className="overflow-hidden rounded-2xl border border-[#dce5e4] bg-white shadow-[0_16px_50px_rgba(28,65,65,.08)]"><div className="min-h-[430px] space-y-4 p-5 sm:p-7">{messages.map((m, i) => <div key={`${m.role}-${i}`} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role === 'user' ? 'bg-[#15252a] text-white' : 'bg-[#eef5f3] text-[#385258]'}`}>{m.content}{m.role === 'assistant' && i === 0 && <div className="mt-3 flex items-center gap-1 text-[10px] text-[#6d8984]"><Check className="size-3" /> Secure conversation</div>}</div></div>)}{send.isPending && <div className="flex"><div className="rounded-2xl bg-[#eef5f3] px-4 py-3"><Loader2 className="size-4 animate-spin text-[#159477]" /></div></div>}</div><form onSubmit={submit} className="flex gap-2 border-t border-[#e6eeec] bg-[#fbfdfc] p-4"><Input data-testid="input-public-chat" value={input} onChange={e => setInput(e.target.value)} placeholder="Type your message..." className="h-11 border-[#dce5e4] bg-white" /><Button type="submit" data-testid="button-public-chat-send" size="icon" className="size-11 shrink-0 rounded-xl"><ArrowUp className="size-4" /></Button></form></div><p className="mt-5 text-center font-mono text-[9px] uppercase tracking-[0.16em] text-[#9aa8a9]">Powered by LeadFlow AI · Your information stays private</p></main></div>;
}
