import { useState } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowRight, Check, ChevronDown, Menu, Play, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Mark } from '@/components/leadflow-ui';

const faqs = [
  ['Does LeadFlow replace my sales team?', 'No. It gives your team the signal and context they need to spend time where intent is highest. The assistant handles the first conversation; people handle the relationship.'],
  ['How quickly can I go live?', 'Most owners are live in an afternoon. Add your services, opening hours, and a few FAQs. LeadFlow takes care of the rest.'],
  ['Where do my leads come from?', 'Every lead keeps its source and conversation attached, so you can see what is working across your website, campaigns, and referrals.'],
  ['Can I pause the assistant?', 'Yes. Automation controls are explicit and reversible. You always decide when follow-ups are sent and when a conversation is handed to you.'],
];

export function LandingPage() {
  const [open, setOpen] = useState<number | null>(0);
  const [menu, setMenu] = useState(false);
  const [, setLocation] = useLocation();
  return <div className="min-h-[100dvh] overflow-hidden bg-[#f4f7f7] text-[#15252a]">
    <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
      <Link href="/" data-testid="link-home"><Mark /></Link>
      <nav className="hidden items-center gap-8 text-sm font-semibold text-[#53656a] md:flex"><a href="#how-it-works" data-testid="link-how-it-works">How it works</a><a href="#use-cases" data-testid="link-use-cases">Use cases</a><Link href="/pricing" data-testid="link-pricing">Pricing</Link></nav>
      <div className="hidden items-center gap-2.5 md:flex"><Link href="/sign-in" data-testid="link-sign-in" className="rounded-lg px-3.5 py-2 text-sm font-bold text-[#53656a] hover:bg-white">Sign in</Link><Button onClick={() => setLocation('/sign-up')} data-testid="button-get-started" className="rounded-lg bg-[#15252a] px-4 text-white hover:bg-[#23383f]">Get started <ArrowRight className="ml-2 size-4" /></Button></div>
      <button type="button" data-testid="button-mobile-nav" className="md:hidden" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button>
    </header>
    {menu && <div className="mx-5 rounded-xl border border-[#dce5e4] bg-white p-4 md:hidden"><div className="grid gap-3 text-sm font-semibold"><a href="#how-it-works">How it works</a><a href="#use-cases">Use cases</a><Link href="/pricing">Pricing</Link><Link href="/sign-in">Sign in</Link></div></div>}
    <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-14 lg:px-8 lg:pb-28 lg:pt-24">
      <div className="pointer-events-none absolute -right-36 -top-28 size-[560px] rounded-full bg-[#c9f0e7] opacity-60 blur-3xl" />
      <div className="relative grid items-center gap-16 lg:grid-cols-[1.03fr_.97fr]">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#b7ddd5] bg-[#e4f6f1] px-3 py-1.5 font-mono text-[10px] font-medium uppercase tracking-[0.16em] text-[#167461]"><span className="size-1.5 rounded-full bg-[#20aa8d]" />Intelligence for high-intent demand</div><h1 className="max-w-2xl text-[52px] font-extrabold leading-[.98] tracking-[-0.075em] text-[#15252a] sm:text-7xl">Know who’s ready <span className="text-[#159477]">before</span> they ask.</h1><p className="mt-7 max-w-lg text-base leading-7 text-[#607277]">LeadFlow AI turns every website conversation into a clear next move — qualified, scored, and ready for your attention.</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={() => setLocation('/sign-up')} data-testid="button-hero-start" className="h-12 rounded-lg bg-[#15252a] px-5 text-white hover:bg-[#23383f]">Start capturing demand <ArrowRight className="ml-2 size-4" /></Button><a href="#how-it-works" data-testid="link-hero-demo" className="flex h-12 items-center gap-2 rounded-lg border border-[#cfdcda] bg-white px-5 text-sm font-bold text-[#33484d] hover:bg-[#f8fbfa]"><Play className="size-3.5 fill-current" /> See how it works</a></div><div className="mt-9 flex items-center gap-6 text-xs font-semibold text-[#758589]"><span className="flex items-center gap-1.5"><ShieldCheck className="size-4 text-[#159477]" /> No credit card</span><span className="flex items-center gap-1.5"><Check className="size-4 text-[#159477]" /> 14-day free trial</span></div></div>
        <div className="relative"><div className="absolute -inset-5 rounded-[28px] bg-[#dcece9]" /><div className="relative overflow-hidden rounded-2xl border border-[#cedddb] bg-white shadow-[0_24px_80px_rgba(28,65,65,.14)]"><div className="flex items-center justify-between border-b border-[#e8efee] px-5 py-4"><div className="flex items-center gap-2"><div className="size-2 rounded-full bg-[#1db58f]" /><span className="text-xs font-bold">LeadFlow assistant</span></div><span className="font-mono text-[9px] uppercase tracking-widest text-[#819195]">Live preview</span></div><div className="grid grid-cols-[.74fr_1.26fr]"><div className="border-r border-[#e8efee] bg-[#f8fbfa] p-4"><div className="mb-5 font-mono text-[9px] uppercase tracking-widest text-[#91a19f]">Today</div>{['Maya Chen','Jordan Reed','Amara Lewis'].map((name, i) => <div key={name} className={`mb-2 rounded-lg p-2.5 ${i === 0 ? 'bg-white shadow-sm ring-1 ring-[#dce7e4]' : ''}`}><div className="flex items-center gap-2"><div className="flex size-6 items-center justify-center rounded-full bg-[#f9c96b] text-[9px] font-bold text-[#5b4721]">{name.split(' ').map(n => n[0]).join('')}</div><div><div className="text-[10px] font-bold">{name}</div><div className="text-[9px] text-[#94a09f]">Website chat</div></div></div><div className="mt-2 flex justify-between"><span className="font-mono text-[9px] text-[#1c967b]">92 score</span><span className="text-[9px] text-[#8f9b9c]">2m</span></div></div>)}</div><div className="p-5"><div className="mb-7 flex items-center justify-between"><div><div className="font-mono text-[9px] uppercase tracking-widest text-[#91a19f]">Qualified lead</div><div className="mt-1 text-lg font-extrabold">Maya Chen</div></div><div className="flex size-12 items-center justify-center rounded-full border-[5px] border-[#c9f0e7] font-mono text-sm font-bold text-[#16836e]">92</div></div><div className="space-y-3"><div className="rounded-lg bg-[#f5f9f8] p-3 text-[11px] leading-5 text-[#607277]">“We need a kitchen renovation quote for a project starting in September.”</div><div className="ml-8 rounded-lg bg-[#e4f6f1] p-3 text-[11px] leading-5 text-[#315e56]">Strong timeline and service fit. Recommend a personal follow-up today.</div></div><div className="mt-6 border-t border-[#e8efee] pt-4"><div className="flex justify-between text-[10px]"><span className="text-[#819195]">Suggested next step</span><span className="font-bold text-[#16836e]">Call Maya</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#e8efee]"><div className="h-full w-[92%] rounded-full bg-[#1db58f]" /></div></div></div></div></div></div>
      </div>
    </section>
    <section className="border-y border-[#dfe9e7] bg-white py-6"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-12 gap-y-3 px-5 text-center font-mono text-[10px] uppercase tracking-[0.18em] text-[#829092] lg:justify-between lg:px-8"><span>Built for owners who follow through</span><span>Service businesses</span><span>High-intent conversations</span><span>Revenue clarity</span></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-xl"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#159477]">From chat to clarity</div><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">A better first five minutes.</h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-[#dce5e4] bg-[#dce5e4] md:grid-cols-3">{[['01','Listen','Every visitor gets a useful answer, not a dead-end form.'],['02','Understand','AI picks up the service, budget, timing, and location signals that matter.'],['03','Prioritize','Your workspace shows the next best move, while low-intent noise stays quiet.']].map(([num, title, copy]) => <div key={num} className="bg-[#f4f7f7] p-7"><div className="font-mono text-xs text-[#159477]">{num}</div><h3 className="mt-14 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66797d]">{copy}</p></div>)}</div></section>
    <section id="use-cases" className="bg-[#15252a] py-24 text-[#eef6f4]"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#53ceb0]">Made for momentum</div><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Stop guessing which conversations matter.</h2><p className="mt-5 max-w-md text-sm leading-6 text-[#a9bebc]">LeadFlow gives independent teams the same signal advantage as a much larger sales operation.</p></div><div className="grid gap-3 sm:grid-cols-2">{[['Home services','Quote requests with a real timeline.'],['Professional services','More context before the discovery call.'],['Health & wellness','A thoughtful answer after hours.'],['Local retail','Turn product questions into visits.']].map(([title, copy], i) => <div key={title} className="rounded-xl border border-[#345157] bg-[#1d3439] p-5"><div className="mb-10 flex size-9 items-center justify-center rounded-lg bg-[#26484a] text-[#53ceb0]">{i === 0 ? <Target className="size-4" /> : <Sparkles className="size-4" />}</div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#9bb2b0]">{copy}</p></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid items-start gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#159477]">Common questions</div><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em]">Worth knowing.</h2></div><div>{faqs.map(([q, a], i) => <div key={q} className="border-t border-[#dce5e4] py-5"><button type="button" data-testid={`button-faq-${i}`} onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between text-left text-sm font-bold">{q}<ChevronDown className={`size-4 transition-transform ${open === i ? 'rotate-180 text-[#159477]' : 'text-[#879795]'}`} /></button>{open === i && <p className="mt-3 max-w-xl text-sm leading-6 text-[#66797d]">{a}</p>}</div>)}</div></div></section>
    <section className="mx-5 mb-8 overflow-hidden rounded-2xl bg-[#d7f1e9] lg:mx-auto lg:max-w-7xl"><div className="flex flex-col items-start justify-between gap-8 px-7 py-10 sm:flex-row sm:items-center sm:px-12 sm:py-12"><div><h2 className="text-3xl font-extrabold tracking-[-0.06em]">Make the next conversation count.</h2><p className="mt-2 text-sm text-[#52716c]">Your best leads are already trying to reach you.</p></div><Button onClick={() => setLocation('/sign-up')} data-testid="button-bottom-start" className="shrink-0 bg-[#15252a] text-white hover:bg-[#23383f]">Get started free <ArrowRight className="ml-2 size-4" /></Button></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 py-8 text-xs text-[#819092] sm:flex-row lg:px-8"><Mark /><span>© 2025 LeadFlow AI. Built for better follow-up.</span><Link href="/pricing" className="font-semibold text-[#53656a]">Pricing</Link></footer>
  </div>;
}

export function PricingPage() {
  const [, setLocation] = useLocation();
  return <div className="min-h-[100dvh] bg-[#f4f7f7] text-[#15252a]"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/" data-testid="link-pricing-home"><Mark /></Link><div className="flex items-center gap-2"><Link href="/sign-in/*?" data-testid="link-pricing-signin" className="rounded-lg px-3 py-2 text-sm font-bold text-[#53656a]">Sign in</Link><Button onClick={() => setLocation('/sign-up/*?')} data-testid="button-pricing-start" className="bg-[#15252a] text-white">Start free</Button></div></header><main className="mx-auto max-w-7xl px-5 pb-24 pt-16 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#159477]">Simple pricing</div><h1 className="mt-3 text-5xl font-extrabold tracking-[-0.07em]">Pay for signal, not noise.</h1><p className="mt-5 text-sm leading-6 text-[#66797d]">Everything you need to turn more conversations into booked work.</p></div><div className="mx-auto mt-14 grid max-w-5xl gap-4 md:grid-cols-3">{[['Starter','$49','For owners building a consistent follow-up habit.',['AI website assistant','250 conversations / month','Lead scoring & pipeline','Email notifications']],['Growth','$129','For teams with steady demand and more to qualify.',['Everything in Starter','1,500 conversations / month','Automated follow-up','Source & service analytics']],['Scale','$249','For multi-location teams with a serious sales motion.',['Everything in Growth','Unlimited team seats','Custom knowledge base','Priority support']]].map(([name, price, copy, features], i) => <div key={name as string} className={`rounded-2xl border p-7 ${i === 1 ? 'border-[#159477] bg-[#15252a] text-white shadow-xl' : 'border-[#dce5e4] bg-white'}`}><div className={`font-mono text-[10px] uppercase tracking-[0.18em] ${i === 1 ? 'text-[#53ceb0]' : 'text-[#159477]'}`}>{name}</div><div className="mt-4 flex items-end gap-1"><span className="text-5xl font-extrabold tracking-[-0.08em]">{price}</span><span className={`mb-2 text-xs ${i === 1 ? 'text-[#9bb2b0]' : 'text-[#829092]'}`}>/ month</span></div><p className={`mt-3 min-h-12 text-sm leading-6 ${i === 1 ? 'text-[#a9bebc]' : 'text-[#66797d]'}`}>{copy}</p><Button onClick={() => setLocation('/sign-up/*?')} data-testid={`button-plan-${name}`} className={`mt-7 w-full ${i === 1 ? 'bg-[#53ceb0] text-[#15252a] hover:bg-[#6fd8c0]' : 'bg-[#15252a] text-white'}`}>Choose {name}</Button><div className={`my-7 h-px ${i === 1 ? 'bg-[#345157]' : 'bg-[#e5eceb]'}`} /> <ul className="space-y-3">{(features as string[]).map(f => <li key={f} className={`flex gap-2 text-xs ${i === 1 ? 'text-[#d1e4e0]' : 'text-[#53656a]'}`}><Check className={`size-4 shrink-0 ${i === 1 ? 'text-[#53ceb0]' : 'text-[#159477]'}`} />{f}</li>)}</ul></div>)}</div></main></div>;
}
